/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChainOfCommandDothtmlIndexRouteImport } from './routes/chain-of-command[.]html/index'
import { Route as HandbookDothtmlIndexRouteImport } from './routes/handbook[.]html/index'
import { Route as Hspu_app_newDothtmlIndexRouteImport } from './routes/hspu_app_new[.]html/index'
import { Route as IndexDothtmlIndexRouteImport } from './routes/index[.]html/index'
import { Route as Official_mediaDothtmlIndexRouteImport } from './routes/official_media[.]html/index'
import { Route as Srt_app_newDothtmlIndexRouteImport } from './routes/srt_app_new[.]html/index'
import { Route as TroopersDothtmlIndexRouteImport } from './routes/troopers[.]html/index'
import { Route as VehicleGuidelinesDothtmlIndexRouteImport } from './routes/vehicle-guidelines[.]html/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChainOfCommandDothtmlIndexRoute =
  ChainOfCommandDothtmlIndexRouteImport.update({
    id: '/chain-of-command.html/',
    path: '/chain-of-command.html/',
    getParentRoute: () => rootRouteImport,
  } as any)
const HandbookDothtmlIndexRoute = HandbookDothtmlIndexRouteImport.update({
  id: '/handbook.html/',
  path: '/handbook.html/',
  getParentRoute: () => rootRouteImport,
} as any)
const Hspu_app_newDothtmlIndexRoute =
  Hspu_app_newDothtmlIndexRouteImport.update({
    id: '/hspu_app_new.html/',
    path: '/hspu_app_new.html/',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexDothtmlIndexRoute = IndexDothtmlIndexRouteImport.update({
  id: '/index.html/',
  path: '/index.html/',
  getParentRoute: () => rootRouteImport,
} as any)
const Official_mediaDothtmlIndexRoute =
  Official_mediaDothtmlIndexRouteImport.update({
    id: '/official_media.html/',
    path: '/official_media.html/',
    getParentRoute: () => rootRouteImport,
  } as any)
const Srt_app_newDothtmlIndexRoute = Srt_app_newDothtmlIndexRouteImport.update({
  id: '/srt_app_new.html/',
  path: '/srt_app_new.html/',
  getParentRoute: () => rootRouteImport,
} as any)
const TroopersDothtmlIndexRoute = TroopersDothtmlIndexRouteImport.update({
  id: '/troopers.html/',
  path: '/troopers.html/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehicleGuidelinesDothtmlIndexRoute =
  VehicleGuidelinesDothtmlIndexRouteImport.update({
    id: '/vehicle-guidelines.html/',
    path: '/vehicle-guidelines.html/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chain-of-command.html/': typeof ChainOfCommandDothtmlIndexRoute
  '/handbook.html/': typeof HandbookDothtmlIndexRoute
  '/hspu_app_new.html/': typeof Hspu_app_newDothtmlIndexRoute
  '/index.html/': typeof IndexDothtmlIndexRoute
  '/official_media.html/': typeof Official_mediaDothtmlIndexRoute
  '/srt_app_new.html/': typeof Srt_app_newDothtmlIndexRoute
  '/troopers.html/': typeof TroopersDothtmlIndexRoute
  '/vehicle-guidelines.html/': typeof VehicleGuidelinesDothtmlIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chain-of-command.html': typeof ChainOfCommandDothtmlIndexRoute
  '/handbook.html': typeof HandbookDothtmlIndexRoute
  '/hspu_app_new.html': typeof Hspu_app_newDothtmlIndexRoute
  '/index.html': typeof IndexDothtmlIndexRoute
  '/official_media.html': typeof Official_mediaDothtmlIndexRoute
  '/srt_app_new.html': typeof Srt_app_newDothtmlIndexRoute
  '/troopers.html': typeof TroopersDothtmlIndexRoute
  '/vehicle-guidelines.html': typeof VehicleGuidelinesDothtmlIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chain-of-command.html/': typeof ChainOfCommandDothtmlIndexRoute
  '/handbook.html/': typeof HandbookDothtmlIndexRoute
  '/hspu_app_new.html/': typeof Hspu_app_newDothtmlIndexRoute
  '/index.html/': typeof IndexDothtmlIndexRoute
  '/official_media.html/': typeof Official_mediaDothtmlIndexRoute
  '/srt_app_new.html/': typeof Srt_app_newDothtmlIndexRoute
  '/troopers.html/': typeof TroopersDothtmlIndexRoute
  '/vehicle-guidelines.html/': typeof VehicleGuidelinesDothtmlIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chain-of-command.html/'
    | '/handbook.html/'
    | '/hspu_app_new.html/'
    | '/index.html/'
    | '/official_media.html/'
    | '/srt_app_new.html/'
    | '/troopers.html/'
    | '/vehicle-guidelines.html/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chain-of-command.html'
    | '/handbook.html'
    | '/hspu_app_new.html'
    | '/index.html'
    | '/official_media.html'
    | '/srt_app_new.html'
    | '/troopers.html'
    | '/vehicle-guidelines.html'
  id:
    | '__root__'
    | '/'
    | '/chain-of-command.html/'
    | '/handbook.html/'
    | '/hspu_app_new.html/'
    | '/index.html/'
    | '/official_media.html/'
    | '/srt_app_new.html/'
    | '/troopers.html/'
    | '/vehicle-guidelines.html/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChainOfCommandDothtmlIndexRoute: typeof ChainOfCommandDothtmlIndexRoute
  HandbookDothtmlIndexRoute: typeof HandbookDothtmlIndexRoute
  Hspu_app_newDothtmlIndexRoute: typeof Hspu_app_newDothtmlIndexRoute
  IndexDothtmlIndexRoute: typeof IndexDothtmlIndexRoute
  Official_mediaDothtmlIndexRoute: typeof Official_mediaDothtmlIndexRoute
  Srt_app_newDothtmlIndexRoute: typeof Srt_app_newDothtmlIndexRoute
  TroopersDothtmlIndexRoute: typeof TroopersDothtmlIndexRoute
  VehicleGuidelinesDothtmlIndexRoute: typeof VehicleGuidelinesDothtmlIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chain-of-command.html/': {
      id: '/chain-of-command.html/'
      path: '/chain-of-command.html'
      fullPath: '/chain-of-command.html/'
      preLoaderRoute: typeof ChainOfCommandDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handbook.html/': {
      id: '/handbook.html/'
      path: '/handbook.html'
      fullPath: '/handbook.html/'
      preLoaderRoute: typeof HandbookDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hspu_app_new.html/': {
      id: '/hspu_app_new.html/'
      path: '/hspu_app_new.html'
      fullPath: '/hspu_app_new.html/'
      preLoaderRoute: typeof Hspu_app_newDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/index.html/': {
      id: '/index.html/'
      path: '/index.html'
      fullPath: '/index.html/'
      preLoaderRoute: typeof IndexDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/official_media.html/': {
      id: '/official_media.html/'
      path: '/official_media.html'
      fullPath: '/official_media.html/'
      preLoaderRoute: typeof Official_mediaDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/srt_app_new.html/': {
      id: '/srt_app_new.html/'
      path: '/srt_app_new.html'
      fullPath: '/srt_app_new.html/'
      preLoaderRoute: typeof Srt_app_newDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/troopers.html/': {
      id: '/troopers.html/'
      path: '/troopers.html'
      fullPath: '/troopers.html/'
      preLoaderRoute: typeof TroopersDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicle-guidelines.html/': {
      id: '/vehicle-guidelines.html/'
      path: '/vehicle-guidelines.html'
      fullPath: '/vehicle-guidelines.html/'
      preLoaderRoute: typeof VehicleGuidelinesDothtmlIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChainOfCommandDothtmlIndexRoute: ChainOfCommandDothtmlIndexRoute,
  HandbookDothtmlIndexRoute: HandbookDothtmlIndexRoute,
  Hspu_app_newDothtmlIndexRoute: Hspu_app_newDothtmlIndexRoute,
  IndexDothtmlIndexRoute: IndexDothtmlIndexRoute,
  Official_mediaDothtmlIndexRoute: Official_mediaDothtmlIndexRoute,
  Srt_app_newDothtmlIndexRoute: Srt_app_newDothtmlIndexRoute,
  TroopersDothtmlIndexRoute: TroopersDothtmlIndexRoute,
  VehicleGuidelinesDothtmlIndexRoute: VehicleGuidelinesDothtmlIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
